### ISSUE TITLE
update ember-cli-babel

### ISSUE THREAD

**Issue by ddengler** [gdong42/ember-qrcode-shim#3]
> DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: xxx -> ember-qrcode-shim -> ember-cli-babel

We are currently just using this in a demo, but wanted to let you know anyway.

**Comment by gdong42** [comment]
@ddengler Thanks for your feedback. This should have been fixed in 0.3.0.

**Comment by ddengler** [comment]
@gdong42 thanks! Just upgraded. Can confirm this is fixed.
